-- AlterTable
ALTER TABLE "User" ADD COLUMN     "monthlyAiResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "monthlyAiUsage" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "monthlyEditResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "monthlyEditUsage" INTEGER NOT NULL DEFAULT 0;
