"use client";

import {
  BarChart,
  Bar,
  LineChart,
  Line,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
} from "recharts";

interface ChartDef {
  label: string;
  type: "bar" | "line" | "pie" | string;
  entity: string;
  groupBy: string;
  value?: string;
}

interface ChartPoint {
  group: string;
  value: number;
}

interface ChartInfo {
  chart: ChartDef;
  data: ChartPoint[];
  purpose: string;
  insight: string;
}

const COLORS = [
  "#0a0a0a",
  "#525252",
  "#a3a3a3",
  "#404040",
  "#737373",
  "#262626",
  "#8c8c8c",
  "#d4d4d4",
  "#171717",
  "#666666",
];

export default function Charts({ charts }: { charts: ChartInfo[] }) {
  if (charts.length === 0) return null;

  return (
    <div
      className={`mb-6 grid gap-4 ${
        charts.length === 1
          ? "grid-cols-1"
          : charts.length === 2
            ? "grid-cols-1 md:grid-cols-2"
            : "grid-cols-1 md:grid-cols-3"
      }`}
    >
      {charts.map((info, i) => (
        <ChartCard key={i} info={info} />
      ))}
    </div>
  );
}

function ChartCard({ info }: { info: ChartInfo }) {
  const { chart, data, purpose, insight } = info;

  return (
    <div className="bg-white rounded-lg shadow flex flex-col">
      {/* Header */}
      <div className="p-4 pb-2">
        <p className="text-sm font-semibold text-gray-900">{chart.label}</p>
        <p className="text-xs text-gray-500 mt-0.5">{purpose}</p>
      </div>

      {/* Chart */}
      <div className="px-4" style={{ width: "100%", height: 200 }}>
        {data.length === 0 ? (
          <div className="flex items-center justify-center h-full text-sm text-gray-400">
            No data
          </div>
        ) : (
          <ResponsiveContainer width="100%" height="100%">
            {renderChart(chart.type, data)}
          </ResponsiveContainer>
        )}
      </div>

      {/* Insight */}
      {data.length > 0 && (
        <div className="px-4 pb-4 pt-3 mt-2 border-t border-gray-100">
          <p className="text-xs text-gray-600 leading-relaxed">
            <span className="mr-1">💡</span>
            <span dangerouslySetInnerHTML={{ __html: renderInsight(insight) }} />
          </p>
        </div>
      )}
    </div>
  );
}

/**
 * Converts **bold** markdown into <strong> tags safely.
 * The insight text is generated by our own code, so it's safe.
 */
function renderInsight(text: string): string {
  return text.replace(
    /\*\*(.+?)\*\*/g,
    '<strong class="text-gray-900">$1</strong>'
  );
}

function renderChart(type: string, data: ChartPoint[]) {
  if (type === "line") {
    return (
      <LineChart data={data} margin={{ top: 5, right: 5, bottom: 5, left: 5 }}>
        <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
        <XAxis
          dataKey="group"
          tick={{ fontSize: 10 }}
          stroke="#9ca3af"
          interval="preserveStartEnd"
        />
        <YAxis tick={{ fontSize: 10 }} stroke="#9ca3af" />
        <Tooltip
          contentStyle={{
            fontSize: 12,
            border: "1px solid #e5e5e5",
            borderRadius: 6,
          }}
        />
        <Line
          type="monotone"
          dataKey="value"
          stroke="#0a0a0a"
          strokeWidth={2}
          dot={{ r: 2, fill: "#0a0a0a" }}
        />
      </LineChart>
    );
  }

  if (type === "pie") {
    return (
      <PieChart>
        <Pie
          data={data}
          dataKey="value"
          nameKey="group"
          cx="50%"
          cy="50%"
          outerRadius={70}
          innerRadius={0}
          label={false}
        >
          {data.map((_, i) => (
            <Cell key={i} fill={COLORS[i % COLORS.length]} />
          ))}
        </Pie>
        <Tooltip
          contentStyle={{
            fontSize: 12,
            border: "1px solid #e5e5e5",
            borderRadius: 6,
          }}
        />
        <Legend
          wrapperStyle={{ fontSize: 11 }}
          layout="horizontal"
          verticalAlign="bottom"
        />
      </PieChart>
    );
  }

  return (
    <BarChart data={data} margin={{ top: 5, right: 5, bottom: 5, left: 5 }}>
      <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
      <XAxis
        dataKey="group"
        tick={{ fontSize: 10 }}
        stroke="#9ca3af"
        interval={0}
        angle={data.length > 6 ? -25 : 0}
        textAnchor={data.length > 6 ? "end" : "middle"}
        height={data.length > 6 ? 55 : 30}
      />
      <YAxis tick={{ fontSize: 10 }} stroke="#9ca3af" />
      <Tooltip
        contentStyle={{
          fontSize: 12,
          border: "1px solid #e5e5e5",
          borderRadius: 6,
        }}
      />
      <Bar dataKey="value" fill="#0a0a0a" radius={[3, 3, 0, 0]} />
    </BarChart>
  );
}