export interface ChartPoint {
  group: string;
  value: number;
}

export interface ChartDef {
  label: string;
  type: "bar" | "line" | "pie" | string;
  groupBy: string;
  value?: string;
}

/**
 * Generates a plain-English description of what a chart shows.
 * All numbers come from the actual data — nothing is generated by AI.
 */
export function describeChart(
  chart: ChartDef,
  data: ChartPoint[]
): { purpose: string; insight: string } {
  if (!data || data.length === 0) {
    return {
      purpose: purposeText(chart),
      insight: "No data to summarize yet.",
    };
  }

  switch (chart.type) {
    case "line":
      return {
        purpose: purposeText(chart),
        insight: trendInsight(data, chart),
      };
    case "pie":
      return {
        purpose: purposeText(chart),
        insight: distributionInsight(data, chart),
      };
    default:
      return {
        purpose: purposeText(chart),
        insight: rankingInsight(data, chart),
      };
  }
}

/* ------------------------------------------------------------------ */
/* Purpose — one sentence saying what the chart is about               */
/* ------------------------------------------------------------------ */

function purposeText(chart: ChartDef): string {
  const byField = humanize(chart.groupBy);
  const valField = chart.value ? humanize(chart.value) : null;

  if (valField) {
    return `How ${valField} is distributed across each ${byField}.`;
  }
  return `How records are distributed across each ${byField}.`;
}

/* ------------------------------------------------------------------ */
/* Ranking insight — for bar / pie charts                              */
/* ------------------------------------------------------------------ */

function rankingInsight(data: ChartPoint[], chart: ChartDef): string {
  const sorted = [...data].sort((a, b) => b.value - a.value);
  const top = sorted[0];
  const bottom = sorted[sorted.length - 1];

  const valueWord = chart.value ? humanize(chart.value) : "records";
  const groupWord = humanize(chart.groupBy);

  // Single group
  if (sorted.length === 1) {
    return `Only one ${groupWord} group: ${top.group} with ${formatNumber(
      top.value
    )} ${valueWord}.`;
  }

  // Compute share for top item
  const total = sorted.reduce((a, b) => a + b.value, 0);
  const topShare = total > 0 ? Math.round((top.value / total) * 100) : 0;

  let text = `**${top.group}** leads with ${formatNumber(top.value)} ${valueWord}`;

  if (topShare >= 40 && sorted.length > 2) {
    text += ` (${topShare}% of all ${valueWord})`;
  } else if (sorted[1]) {
    // Mention runner-up only if not dominated
    text += `, followed by ${sorted[1].group} with ${formatNumber(
      sorted[1].value
    )}`;
  }
  text += ".";

  // Add notable contrast
  if (sorted.length >= 3 && bottom.value === 0) {
    text += ` ${bottom.group} has no ${valueWord}.`;
  } else if (
    sorted.length >= 3 &&
    top.value >= bottom.value * 3 &&
    bottom.value > 0
  ) {
    text += ` The lowest is ${bottom.group} with ${formatNumber(
      bottom.value
    )}.`;
  }

  return text;
}

/* ------------------------------------------------------------------ */
/* Trend insight — for line charts                                     */
/* ------------------------------------------------------------------ */

function trendInsight(data: ChartPoint[], chart: ChartDef): string {
  if (data.length === 1) {
    return `Only one data point: ${data[0].group}.`;
  }

  const valueWord = chart.value ? humanize(chart.value) : "records";
  const first = data[0];
  const last = data[data.length - 1];

  const diff = last.value - first.value;
  const pctChange =
    first.value !== 0 ? Math.round((diff / first.value) * 100) : 0;

  // Direction
  let direction: "up" | "down" | "flat";
  if (Math.abs(pctChange) < 5) direction = "flat";
  else if (diff > 0) direction = "up";
  else direction = "down";

  // Peak / trough
  const sorted = [...data].sort((a, b) => b.value - a.value);
  const peak = sorted[0];

  const parts: string[] = [];

  if (direction === "up") {
    parts.push(
      `${valueWord} grew from ${formatNumber(first.value)} in ${first.group} to ${formatNumber(
        last.value
      )} in ${last.group} (${pctChange > 0 ? "+" : ""}${pctChange}%)`
    );
  } else if (direction === "down") {
    parts.push(
      `${valueWord} decreased from ${formatNumber(first.value)} in ${first.group} to ${formatNumber(
        last.value
      )} in ${last.group} (${pctChange}%)`
    );
  } else {
    parts.push(
      `${valueWord} stayed fairly steady, from ${formatNumber(first.value)} in ${first.group} to ${formatNumber(
        last.value
      )} in ${last.group}`
    );
  }

  if (peak.group !== last.group && peak.group !== first.group) {
    parts.push(
      `the highest point was ${peak.group} at ${formatNumber(peak.value)}`
    );
  }

  return capitalize(parts.join("; ")) + ".";
}

/* ------------------------------------------------------------------ */
/* Distribution insight — for pie charts                                */
/* ------------------------------------------------------------------ */

function distributionInsight(data: ChartPoint[], chart: ChartDef): string {
  const valueWord = chart.value ? humanize(chart.value) : "records";
  const groupWord = humanize(chart.groupBy);
  const total = data.reduce((a, b) => a + b.value, 0);

  if (total === 0) {
    return "No measurable data yet.";
  }

  const sorted = [...data].sort((a, b) => b.value - a.value);
  const top = sorted[0];
  const topPct = Math.round((top.value / total) * 100);

  // If one group dominates
  if (topPct >= 60) {
    return `${top.group} dominates, making up ${topPct}% of all ${valueWord} across ${data.length} ${groupWord} groups.`;
  }

  // If two groups split most of it
  if (sorted[1]) {
    const secondPct = Math.round((sorted[1].value / total) * 100);
    if (topPct + secondPct >= 70) {
      return `${top.group} and ${sorted[1].group} together account for ${topPct + secondPct}% of all ${valueWord} (${topPct}% and ${secondPct}%).`;
    }
  }

  // Otherwise
  return `${valueWord} is spread across ${data.length} ${groupWord} groups, with ${top.group} leading at ${topPct}%.`;
}

/* ------------------------------------------------------------------ */
/* Utilities                                                           */
/* ------------------------------------------------------------------ */

function humanize(s: string): string {
  return s
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/_/g, " ")
    .toLowerCase();
}

function formatNumber(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n % 1 === 0 ? String(n) : n.toFixed(2);
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}